In [1]:
import pandas as pd
import os 

DATA_DIR = 'data/novozymes-enzyme-stability-prediction'

data = pd.read_csv(os.path.join(DATA_DIR, "test.csv"))
labels = pd.read_csv(os.path.join(DATA_DIR, "test_labels.csv"))
df = pd.concat([data, labels], axis=1)
df = df.sort_values('tm')

seq_wildtype = 'VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVDCWAILCKGAPNVLQRVNEKTKNSNRDRSGANKGPFKDPQKWGIKALPPKNPSWSAQDFKSPEEYAFASSLQGGTNAILAPVNLASQNSQGGVLNGFYSANKVAQFDPSKPQQTKGTWFQITKFTGAAGPYCKALGSNDKSVCDKNKNIAGDWGFDPAKWAYQYDEKNNKFNYVGK'

wt_len =  len(seq_wildtype) # 221, actually only 1 does not have len 221
df['seq_len'] = df.protein_sequence.apply(lambda x: len(x))
df = df[df.seq_len == wt_len]

len(df)

2336

In [2]:
df[df.protein_sequence==seq_wildtype]

,seq_id,protein_sequence,pH,data_source,seq_id,tm,seq_len
1169,32559,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,32559,77.4,221

In [27]:
df.head()

,seq_id,protein_sequence,pH,data_source,seq_id,tm,seq_len
544,31934,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,31934,28.9,221
1745,33135,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,33135,30.0,221
522,31912,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,31912,30.2,221
187,31577,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,31577,30.3,221
566,31956,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,31956,31.9,221

In [28]:
df.tail()

,seq_id,protein_sequence,pH,data_source,seq_id,tm,seq_len
601,31991,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,31991,80.5,221
648,32038,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,32038,80.7,221
615,32005,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,32005,81.0,221
1866,33256,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,33256,81.0,221
1833,33223,VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes,33223,81.7,221

In [32]:
import requests

# Define the API endpoint
api_url = "https://api.esmatlas.com/foldSequence/v1/pdb/"

def get_pdb(protein_sequence: str, fname: str):
    # Send the POST request with the protein sequence in the body
    response = requests.post(api_url, data=protein_sequence)

    # Check if the response is successful (status code 200)
    if response.status_code == 200:
        # Assuming the response contains the predicted protein structure in PDB format
        pdb_data = response.text
        
        # Save the PDB data to a file
        with open(f"{fname}.pdb", "w") as file:
            file.write(pdb_data)
        
        print(f"Protein structure saved as {fname}")
    else:
        print(f"Error {response.status_code}: {response.text}")


# for i, row in df[df.tm==77.4].head(11).reset_index().iterrows():
for i, row in df.head(50).reset_index().iterrows():
    get_pdb(row.protein_sequence, f'data/predicted/low_tm_{row.tm}_{i}')


for i, row in df[df.tm==77.4].head(50).reset_index().iterrows():
    get_pdb(row.protein_sequence, f'data/predicted/similar_tm_{row.tm}_{i}')

Protein structure saved as data/predicted/low_tm_28.9_0
Protein structure saved as data/predicted/low_tm_30.0_1
Protein structure saved as data/predicted/low_tm_30.2_2
Protein structure saved as data/predicted/low_tm_30.3_3
Protein structure saved as data/predicted/low_tm_31.9_4
Protein structure saved as data/predicted/low_tm_37.7_5
Protein structure saved as data/predicted/low_tm_40.6_6
Protein structure saved as data/predicted/low_tm_41.1_7
Protein structure saved as data/predicted/low_tm_41.2_8
Protein structure saved as data/predicted/low_tm_41.5_9
Protein structure saved as data/predicted/low_tm_41.6_10
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_42.5_12
Protein structure saved as data/predicted/low_tm_43.2_13
Protein structure saved as data/predicted/low_tm_44.5_14
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_47.3_16
Protein structure saved as data/predicted/low_tm_47.3_17
Protein structure saved as data/predicted/low_tm_48.7_18
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_50.5_20
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_51.0_22
Error 504: {"message": "Endpoint request timed out"}
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_51.5_25
Protein structure saved as data/predicted/low_tm_51.6_26
Protein structure saved as data/predicted/low_tm_51.9_27
Protein structure saved as data/predicted/low_tm_52.1_28
Protein structure saved as data/predicted/low_tm_52.1_29
Protein structure saved as data/predicted/low_tm_52.1_30
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/low_tm_52.4_32
Protein structure saved as data/predicted/low_tm_52.4_33
Protein structure saved as data/predicted/low_tm_52.4_34
Protein structure saved as data/predicted/low_tm_52.5_35
Protein structure saved as data/predicted/low_tm_52.5_36
Protein structure saved as data/predicted/low_tm_52.6_37
Protein structure saved as data/predicted/low_tm_52.8_38
Protein structure saved as data/predicted/low_tm_52.8_39
Protein structure saved as data/predicted/low_tm_52.8_40
Protein structure saved as data/predicted/low_tm_52.8_41
Protein structure saved as data/predicted/low_tm_52.9_42
Protein structure saved as data/predicted/low_tm_52.9_43
Protein structure saved as data/predicted/low_tm_52.9_44
Protein structure saved as data/predicted/low_tm_53.0_45
Protein structure saved as data/predicted/low_tm_53.1_46
Protein structure saved as data/predicted/low_tm_53.1_47
Protein structure saved as data/predicted/low_tm_53.1_48
Protein structure saved as data/predicted/low_tm_53.2_49
Protein structure saved as data/predicted/similar_tm_77.4_0
Protein structure saved as data/predicted/similar_tm_77.4_1
Protein structure saved as data/predicted/similar_tm_77.4_2
Protein structure saved as data/predicted/similar_tm_77.4_3
Protein structure saved as data/predicted/similar_tm_77.4_4
Protein structure saved as data/predicted/similar_tm_77.4_5
Protein structure saved as data/predicted/similar_tm_77.4_6
Protein structure saved as data/predicted/similar_tm_77.4_7
Protein structure saved as data/predicted/similar_tm_77.4_8
Protein structure saved as data/predicted/similar_tm_77.4_9
Protein structure saved as data/predicted/similar_tm_77.4_10
Protein structure saved as data/predicted/similar_tm_77.4_11
Protein structure saved as data/predicted/similar_tm_77.4_12
Protein structure saved as data/predicted/similar_tm_77.4_13
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/similar_tm_77.4_15
Protein structure saved as data/predicted/similar_tm_77.4_16
Protein structure saved as data/predicted/similar_tm_77.4_17
Protein structure saved as data/predicted/similar_tm_77.4_18
Protein structure saved as data/predicted/similar_tm_77.4_19
Protein structure saved as data/predicted/similar_tm_77.4_20
Protein structure saved as data/predicted/similar_tm_77.4_21
Protein structure saved as data/predicted/similar_tm_77.4_22
Protein structure saved as data/predicted/similar_tm_77.4_23
Protein structure saved as data/predicted/similar_tm_77.4_24
Protein structure saved as data/predicted/similar_tm_77.4_25
Protein structure saved as data/predicted/similar_tm_77.4_26
Protein structure saved as data/predicted/similar_tm_77.4_27
Protein structure saved as data/predicted/similar_tm_77.4_28
Protein structure saved as data/predicted/similar_tm_77.4_29
Protein structure saved as data/predicted/similar_tm_77.4_30
Protein structure saved as data/predicted/similar_tm_77.4_31
Protein structure saved as data/predicted/similar_tm_77.4_32
Protein structure saved as data/predicted/similar_tm_77.4_33
Protein structure saved as data/predicted/similar_tm_77.4_34
Protein structure saved as data/predicted/similar_tm_77.4_35
Error 504: {"message": "Endpoint request timed out"}
Protein structure saved as data/predicted/similar_tm_77.4_37
Protein structure saved as data/predicted/similar_tm_77.4_38
Protein structure saved as data/predicted/similar_tm_77.4_39
Protein structure saved as data/predicted/similar_tm_77.4_40
Protein structure saved as data/predicted/similar_tm_77.4_41
Protein structure saved as data/predicted/similar_tm_77.4_42
Protein structure saved as data/predicted/similar_tm_77.4_43
Protein structure saved as data/predicted/similar_tm_77.4_44
Protein structure saved as data/predicted/similar_tm_77.4_45
Protein structure saved as data/predicted/similar_tm_77.4_46
Protein structure saved as data/predicted/similar_tm_77.4_47
Protein structure saved as data/predicted/similar_tm_77.4_48
Protein structure saved as data/predicted/similar_tm_77.4_49